// <auto-generated />
using System;
using EnglishHelperService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishHelperService.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230902163748_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnglishHelperService.Persistence.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 2, 16, 37, 48, 31, DateTimeKind.Utc).AddTicks(5131));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("LastActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 2, 16, 37, 48, 31, DateTimeKind.Utc).AddTicks(5321));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Member");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            LastActive = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = new byte[] { 122, 228, 210, 115, 80, 255, 174, 216, 176, 54, 164, 214, 196, 236, 75, 140, 248, 191, 59, 104, 244, 143, 232, 30, 82, 69, 82, 12, 103, 54, 196, 175, 105, 96, 214, 28, 243, 58, 146, 75, 211, 37, 165, 134, 88, 56, 79, 51, 183, 214, 43, 237, 52, 128, 175, 222, 13, 0, 167, 157, 216, 20, 24, 89 },
                            PasswordSalt = new byte[] { 21, 102, 213, 180, 254, 141, 20, 184, 82, 176, 184, 80, 199, 255, 129, 34, 76, 247, 214, 82, 105, 99, 174, 87, 226, 221, 214, 24, 143, 220, 188, 74, 44, 9, 76, 146, 129, 218, 161, 39, 134, 35, 149, 216, 35, 120, 130, 69, 189, 188, 193, 5, 73, 164, 241, 89, 135, 230, 136, 56, 4, 235, 183, 208, 200, 191, 91, 73, 152, 197, 62, 126, 18, 188, 68, 230, 80, 193, 250, 142, 59, 61, 123, 25, 93, 54, 46, 26, 245, 134, 55, 75, 30, 218, 226, 158, 126, 7, 216, 10, 0, 130, 237, 51, 187, 141, 240, 223, 186, 238, 15, 98, 230, 129, 4, 154, 19, 102, 140, 134, 18, 223, 58, 59, 151, 23, 122, 188 },
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
