namespace EnglishHelperService.ServiceContracts
{
	public enum ErrorMessage
	{
		INVALID_REQUEST,
		SERVER_ERROR,

		INVALID_PASSWORD_OR_USERNAME,
		USERNAME_REQUIRED,
		USERNAME_EXISTS,
		PASSWORD_REQUIRED,
		INVALID_PASSWORD_LENGTH,
		EMAIL_REQUIRED,
		EMAIL_EXISTS,
		INVALID_EMAILFORMAT,
	}
}